import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/header'

const manrope = Manrope({
  subsets: ['latin'],
})

// px-4 lg:px-20 2xl:px-[162px]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-vibe-black-06`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
